services:
  - type: web
    name: html-to-docx-service-python
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
